### ISSUE TITLE
Fix install with Git+

### ISSUE THREAD

**Issue by melg8** [bkuhlmann/git-lint#9]
## Overview
Can't install git-lint on ubuntu 23.04 because of missing dependency git_plus.

## Screenshots/Screencasts
``` bash
#23 2.034 ERROR:  Could not find a valid gem 'git_plus' (~> 1.7) (required by 'git-lint' (>= 0)) in any repository
#23 6.570 ERROR:  Possible alternatives: git-blur, git-plan, git-pulls, git_ls, git_push, gitius, gitploy, gplus, optplus
```

## Steps to Recreate
In docker do:
``` bash
FROM ubuntu:23.04 as cit

RUN apt-get update \
 && apt-get -y install --no-install-recommends \
    curl=7.88.* \
    ruby-full=1:3.*
    
RUN gem cert --add <(curl --compressed --location https://alchemists.io/gems.pem) \
 && gem install git-lint --trust-policy HighSecurity
 
 ```
It seems this gem were removed from [ruby gems](https://rubygems.org/gems/git_plus).
Also github repository is missing https://github.com/bkuhlmann/git_plus

## Environment
Docker, ubuntu:23.04.

**Comment by bkuhlmann** [comment]
Hey Melg. :wave: Yep, that's correct. Git+ no longer exists and has been completely replaced by [Gitt](https://alchemists.io/projects/gitt). This change occurred in [Version 5.0.0](https://alchemists.io/projects/git-lint/versions). I would recommend upgrading to 5.0.0 or higher. I'm going to close this issue since this is resolved in the current version.
